services:

  nginx:
    image: nginx:alpine
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}  # HTTP port for local development
    environment:
      - CORE_SERVICE_URL=${BACKEND_PROTOCOL}://${CORE_SERVICE_HOST}:${CORE_SERVICE_PORT}
      - AUB_SERVICE_URL=${BACKEND_PROTOCOL}://${AUB_SERVICE_HOST}:${AUB_SERVICE_PORT}/
      - WEBHOOK_HANDLER_URL=${BACKEND_PROTOCOL}://${WEBHOOK_HANDLER_HOST}:${WEBHOOK_HANDLER_PORT}/
      - DOLLAR=$ # To escape $ in envsubst
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf.template
    command: /bin/sh -c "envsubst '$$CORE_SERVICE_URL $$AUB_SERVICE_URL $$WEBHOOK_HANDLER_URL $$DOLLAR' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - aub-service
      - core-service
      - webhook-hendler

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redisdata:/data

  core-service:
    build:
      context: .
      dockerfile: core-service/Dockerfile
    ports:
      - ${CORE_SERVICE_PORT}:${CORE_SERVICE_PORT}
    environment:
      - PORT=${CORE_SERVICE_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - CAMPAIGN_MIN_GAP_MINUTES=${CAMPAIGN_MIN_GAP_MINUTES}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
    depends_on:
      - postgres
      - rabbitmq

  # aub-service:
  aub-service:
    build:
      context: ./aub-service
      dockerfile: Dockerfile
    ports:
      - ${AUB_SERVICE_PORT}:${AUB_SERVICE_PORT}
    environment:
      - PORT=${AUB_SERVICE_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXP_SECONDS=${JWT_EXP_SECONDS}
      - OTP_TTL_SEC=${OTP_TTL_SEC}
      - OTP_QUEUE_NAME=${OTP_QUEUE_NAME}
    depends_on:
      - postgres
      - rabbitmq
      - redis

  outpost-service:
    build:
      context: ./outpost-service
      dockerfile: Dockerfile
    environment:
      - WA_API_B=${WA_API_B}
      - WA_PHONE_ID=${WA_PHONE_ID}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - OUTPOST_QUEUE_NAME=${OUTPOST_QUEUE_NAME}
      - OUTPOST_ENABLE_DB_LOGGING=true
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      - rabbitmq
      - postgres


  schedule-service:
    build:
      context: ./scheduler-service
      dockerfile: Dockerfile
    ports:
      - ${SCHEDUALE_SERVICE_PORT}:${SCHEDUALE_SERVICE_PORT}
    environment:
      - PORT=${SCHEDUALE_SERVICE_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - CAMPAIGNS_QUEUE=${CAMPAIGNS_QUEUE}
    depends_on:
      - postgres
      - rabbitmq

      
  campaign-worker:
    build:
      context: ./campaign-worker
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - CAMPAIGNS_QUEUE=${CAMPAIGNS_QUEUE}
      - OUTPOST_QUEUE_NAME=${OUTPOST_QUEUE_NAME}
      - MEDIA_S3_URL=${MEDIA_S3_URL}
    depends_on:
      - postgres
      - rabbitmq


  # webhook-hendler:
  webhook-hendler:
    build:
      context: ./webhook-hendler
      dockerfile: Dockerfile
    ports:
      - ${WEBHOOK_HANDLER_PORT}:${WEBHOOK_HANDLER_PORT}
    environment:
      - PORT=${WEBHOOK_HANDLER_PORT}
      - WEBHOOK_VERIFY_TOKEN=${WEBHOOK_VERIFY_TOKEN}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - REDIS_URL=${REDIS_URL}
      - WEBHOOK_QUEUE=${WEBHOOK_QUEUE_NAME}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
    depends_on:
      - rabbitmq

     
  webhook-worker:
    build:
      context: ./webhook-worker
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - WEBHOOK_QUEUE=${WEBHOOK_QUEUE_NAME}
      - OUTPOST_QUEUE_NAME=${OUTPOST_QUEUE_NAME}
      - CONVERSATION_INITIAL_STATE=${CONVERSATION_INITIAL_STATE}
      - SECONDARY_BOT_PHONE=${SECONDARY_BOT_PHONE}
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
      core-service:
        condition: service_started


networks:
  default:
    driver: bridge
volumes:
  pgdata:
  redisdata: