"""Alembic environment for core-service.

Reads DATABASE_URL from the environment and targets the SQLAlchemy models'
metadata so future migrations can be autogenerated (`alembic revision --autogenerate`).
"""
from __future__ import annotations

import os

from alembic import context
from sqlalchemy import create_engine, pool

# Importing the models registers all tables on Base.metadata.
from app.db import Base
import app.models.models  # noqa: F401  (side-effect: table registration)

target_metadata = Base.metadata


def _get_url() -> str:
    url = os.getenv("DATABASE_URL")
    if not url:
        raise RuntimeError("DATABASE_URL must be set to run migrations")
    return url


def run_migrations_offline() -> None:
    context.configure(
        url=_get_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        compare_type=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = create_engine(_get_url(), poolclass=pool.NullPool)
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
