version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile  # The Dockerfile for app.py

    ports:
      - "3000:3000"

  cloudflare-tunnel:
      image: cloudflare/cloudflared:latest
      container_name: cloudflare-tunnel
      hostname: cloudflare-tunnel
      restart: unless-stopped
      command: tunnel --no-autoupdate run
      environment:
        - TUNNEL_TOKEN=${TUNNEL_TOKEN}

      depends_on:
        - app

